#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <backup_file.dump> --confirm-replace-target"
  exit 1
fi
if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is required"
  exit 1
fi

SRC="$1"
if [[ ! -s "$SRC" ]]; then
  echo "backup file not found: $SRC"
  exit 1
fi
if [[ "${2:-}" != "--confirm-replace-target" ]]; then
  echo "restore refused: this operation cleans and replaces the target database"
  echo "use only a disposable restore-verification target and pass --confirm-replace-target"
  exit 1
fi

for tool in pg_restore psql; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "Required PostgreSQL restore tool is missing: $tool" >&2
    exit 1
  fi
done
export PGCONNECT_TIMEOUT="${PGCONNECT_TIMEOUT:-10}"
export LC_ALL=C

# Validate the archive and major-version compatibility before cleaning anything.
ARCHIVE_LIST="$(pg_restore --list "$SRC")"
if [[ ! "$ARCHIVE_LIST" =~ Dumped\ by\ pg_dump\ version:\ ([0-9]+)\.[0-9]+ ]]; then
  echo "Cannot determine the archive's pg_dump major version" >&2
  exit 1
fi
DUMP_MAJOR="${BASH_REMATCH[1]}"
SERVER_VERSION="$(psql -X -At --no-password --set ON_ERROR_STOP=1 --dbname "$DATABASE_URL" --command 'SHOW server_version_num')"
SERVER_VERSION="${SERVER_VERSION//$'\r'/}"
if [[ ! "$SERVER_VERSION" =~ ^[0-9]+$ ]]; then
  echo "Cannot determine PostgreSQL target version" >&2
  exit 1
fi
SERVER_MAJOR=$((SERVER_VERSION / 10000))
if (( DUMP_MAJOR > SERVER_MAJOR )); then
  echo "Archive was generated by pg_dump $DUMP_MAJOR, but target is PostgreSQL $SERVER_MAJOR; use a compatible target or recreate the backup with matching client tools" >&2
  exit 1
fi

# A failed restore must roll back its DROP/CREATE/data changes as one unit.
pg_restore --no-password --single-transaction --exit-on-error --clean --if-exists --no-owner --no-privileges --dbname "$DATABASE_URL" "$SRC"
echo "PostgreSQL restore completed"
